---
- hosts: localhost
  connection: local
  become: true
  
  vars:
    base_pkgs:
        - htop
        - neovim
        - net-tools
        - zsh
        - tmux
        - git
        - git-lfs
        - git-extras
        - ansible
        - colorize
        - docker
        - docker-compose


  tasks:

    - name: Install base packages
      apt:
        name: "{{ base_pkgs }}"
        state: present
        update_cache: yes
  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/fredrik-hansen/ansible.git 
