---
- hosts: localhost
  connection: local
  become: true
  
  vars:
    username: pki
    ansible_user: velociraptor
    base_pkgs:
        - htop
        - neovim
        - net-tools
        - zsh
        - tmux
        - git
        - git-lfs
        - git-extras
        - ansible
        - colorize
        - docker
        - docker-compose
        - feh
        - software-properties-common
        - stow
        - clamav
  tasks:

    - name: Install base packages
      apt:
        name: "{{ base_pkgs }}"
        state: present
        update_cache: yes
    - name: add ansible user
      user:
        name: velociraptor
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: files/sudoer_{{ ansible_user }}
        dest: /etc/sudoers.d/{{ ansible_user }}
        owner: root
        group: root
        mode: 0440

    - name: add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: "{{ ansible_user }}"
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/fredrik-hansen/ansible.git 

    - name: Setup zsh from repo
      become: yes
      become_user: "{{ username }}"
      block:
        - name: Clone machfiles repo
          git:
            repo: "https://github.com/fredrik-hansen/machfiles.git"
            dest: "~{{ username }}/Machfiles"
        - name: Setup zsh 
          command: "chdir=~{{ username }}/Machfiles stow zsh"
    - name: Global zprofile
      become: yes
      copy:
        src: files/zprofile
        dest: /etc/zsh/zprofile
        owner: root
        group: root
        mode: 0640

    - name: Change shell to zsh 
      become: yes
      become_user: "{{ username }}"
      command: "chsh -s /bin/zsh {{ username }}"

    - name: Set perms of file pkexec
      file:
        path: /usr/bin/pkexec
        state: file
        owner: root 
        group: root
        mode: 0755


