# Ansible provided network config for amd 
network:
  ethernets:
    enp68s0:
      addresses:
      - 10.9.9.10/24
      optional: true
    enp70s0:
      dhcp4: true
      optional: true
  version: 2

